# Generated by Django 4.0.2 on 2022-02-28 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AID', models.IntegerField(default=0)),
                ('AssetName', models.CharField(max_length=100)),
                ('AssetLink', models.CharField(max_length=100)),
                ('LastUpdated', models.DateField(default=django.utils.timezone.now)),
                ('VersionNum', models.CharField(max_length=100)),
                ('ImgLink', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Key', models.IntegerField(default=1)),
                ('Name', models.CharField(max_length=100)),
                ('Identifier', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LabelName', models.CharField(max_length=100)),
                ('Assets', models.ManyToManyField(to='main.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=100)),
                ('Assets', models.ManyToManyField(to='main.Asset')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='Repos',
            field=models.ManyToManyField(to='main.Repo'),
        ),
    ]
