# Generated by Django 4.0.1 on 2022-01-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='asset_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AID', models.CharField(max_length=100)),
                ('AssetName', models.CharField(max_length=100)),
                ('AssetLink', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('Version', models.CharField(max_length=100)),
                ('ImgLink', models.CharField(max_length=100)),
                ('Keywords', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='class_asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassKey', models.CharField(max_length=100)),
                ('AID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='class_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassKey', models.CharField(max_length=100)),
                ('ProfEmail', models.CharField(max_length=100)),
                ('ClassName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfFirstName', models.CharField(max_length=100)),
                ('ProfLastName', models.CharField(max_length=100)),
                ('ProfEmail', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='student_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=100)),
                ('AID', models.CharField(max_length=100)),
            ],
        ),
    ]
