# Generated by Django 4.0.2 on 2022-02-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='AID',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='CategoryName',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='LabelName',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='repo',
            name='Key',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
