# Generated by Django 4.0.1 on 2022-02-13 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_asset_info_class_asset_class_info_professor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='class_asset',
        ),
        migrations.DeleteModel(
            name='class_info',
        ),
        migrations.DeleteModel(
            name='professor',
        ),
        migrations.DeleteModel(
            name='student',
        ),
        migrations.DeleteModel(
            name='student_class',
        ),
    ]
