# Generated by Django 4.0.1 on 2022-02-13 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_asset_repo_delete_asset_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='id',
        ),
        migrations.RemoveField(
            model_name='repo',
            name='id',
        ),
        migrations.AlterField(
            model_name='asset',
            name='AID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='repo',
            name='AID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.asset'),
        ),
        migrations.AlterField(
            model_name='repo',
            name='RepoKey',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
