# Generated by Django 4.0.1 on 2022-02-15 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_asset_id_remove_repo_id_alter_asset_aid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repo',
            name='AID',
        ),
        migrations.DeleteModel(
            name='asset',
        ),
        migrations.DeleteModel(
            name='repo',
        ),
    ]
