# Generated by Django 4.0.2 on 2022-02-16 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='Description',
            new_name='VersionNum',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='Keywords',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='Version',
        ),
        migrations.AddField(
            model_name='asset',
            name='LastUpdated',
            field=models.DateField(default=datetime.date(2022, 2, 16)),
        ),
    ]
