# Generated by Django 4.0.1 on 2022-02-17 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_repo_aid_asset_repokey_label_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='LastUpdated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
